version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: toxicbakery/alpine-glibc-android:latest-ndk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: ./gradlew build

