version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: toxicbakery/alpine-glibc-android:release-ndk-1.1.1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: echo "signing.keyId=${SIGNING_KEY}" >> "gradle.properties"
      - run: echo "signing.password=${SIGNING_PASSWORD}" >> "gradle.properties"
      - run: echo "signing.secretKeyRingFile=../private.asc" >> "gradle.properties"
      - run: openssl aes-256-cbc -d -in private.asc.enc -out private.asc -k $ENC_FILE_KEY
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Build" 
          command: ./gradlew build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: Sonatype
